version: '3.3'

services:
  mongodb:
    image: mongo:6.0   # MongoDB image
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"  # Expose MongoDB on localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Root username
      MONGO_INITDB_ROOT_PASSWORD: password  # Root password
    volumes:
      - /rooot/pkr:/data/db  # Persistent storage for MongoDB

  nginx:
    image: nginx:latest  # Nginx image
    container_name: nginx_container
    restart: always
    ports:
      - "82:80"  # Map Nginx to localhost port 80
    volumes:
      - /root/pkr/Dockerfile/nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx config
      - /root/pkr/Dockerfile/html/:/usr/share/nginx/html:ro  # Serve static files

volumes:
  mongo_data: {}  # Named volume for MongoDB
